In [1]:
import numpy as np
import cv2

In [2]:
img1=np.zeros((512,512,3),np.uint8)# create an array of shape(512,512),3 matrix one behind each other.
#uint8: Unsigned integer of 8 bits

In [3]:
img=cv2.imread(r'C:\Users\anit\Downloads\opencv-4.x\opencv-4.x\samples\data\lena.jpg')
print(img.shape)

(512, 512, 3)


#### Line

In [4]:
cv2.line(img,(10,10),(255,255),(56,255,100),5)
# 5:Line width
#(10,10)-Starting point of line
#(255,255)-Ending point of line
#(0,255,0):RGB
cv2.line(img1,(20,20),(300,300),(56,255,100),5)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

#### Arrowed Line

In [5]:
cv2.arrowedLine(img,(67,90),(500,500),(56,255,100),5)#We will get arrowed line
cv2.arrowedLine(img1,(10,10),(255,255),(56,255,100),5)


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

#### Rectangle

In [6]:
cv2.rectangle(img,(101,20),(200,40),(0,255,0),3)
cv2.rectangle(img1,(101,20),(200,40),(0,255,0),3)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

#### Circle

In [7]:
cv2.circle(img,(55,55),100,(0,0,255),-1)#-1 fills the colour of circle with red
cv2.circle(img1,(55,55),100,(0,0,255),-1)

array([[[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

#### Adding Text

In [39]:
cv2.putText(img,"Wow",(2,56),cv2.FONT_HERSHEY_SIMPLEX, 1,(255,0,0),1)

array([[[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [126, 145, 236],
        [110, 129, 220],
        [ 86, 104, 197]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [130, 150, 235],
        [112, 132, 217],
        [ 83, 102, 189]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [127, 148, 230],
        [112, 133, 215],
        [ 85, 105, 190]],

       ...,

       [[ 55,  21,  82],
        [ 54,  20,  81],
        [ 62,  28,  92],
        ...,
        [ 82,  71, 175],
        [ 78,  68, 175],
        [ 74,  65, 175]],

       [[ 55,  18,  80],
        [ 56,  19,  81],
        [ 66,  32,  96],
        ...,
        [ 82,  69, 177],
        [ 80,  71, 181],
        [ 81,  72, 183]],

       [[ 56,  19,  81],
        [ 58,  21,  83],
        [ 68,  34,  98],
        ...,
        [ 81,  68, 176],
        [ 81,  72, 183],
        [ 84,  74, 188]]

In [40]:
cv2.imshow("image",img)
cv2.imshow("image shape",img1)
cv2.waitKey()
cv2.destroyAllWindows()